name: Release Meeting Assistant

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v4
      with:
        version:      '6.8.2'
        host:         'windows'
        target:       'desktop'
        arch:         'win64_msvc2022_64'
        modules:      'qtcharts qtnetworkauth qtmultimedia'
        install-deps: true
        dir:          'C:/Qt'
    
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
    
    - name: Configure
      shell: cmd
      run: |
        set PATH=C:\Qt\6.8.2\msvc2022_64\bin;%PATH%
        qmake
        
    - name: Build
      shell: cmd
      run: |
        nmake
        
    - name: Copy DLLs
      shell: cmd
      run: |
        windeployqt --release --qmldir . release\MeetingAssistant.exe
        
    - name: Copy Azure Speech SDK DLLs
      shell: cmd
      run: |
        xcopy /Y /E MeetingAssistant\third_party\azure_speech_sdk\bin\*.dll release\
        
    - name: Compress Release
      shell: cmd
      run: |
        powershell Compress-Archive -Path release\* -DestinationPath release.zip
        
    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: MeetingAssistant
        path: release.zip
        retention-days: 30 
